http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline/logstash.conf
path.settings: /usr/share/logstash/config/logstash.yml
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: http://benben.elasticsearch.host:9200