spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ffms_db
    username: root
    password:
    validationQuery: "SELECT 1"
    timeBetweenEvictionRunsMillis: 300000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update

server:
  port: 8080
  context-path: /ffms
